In [31]:
val = [("Popo",2007,8.6),("Dodo",2009,6.7),("Lolo",2004,9.2)]
dtype1 = [("name",'S10'),("year",int),("gpa",float)]
arr = np.array(val,dtype=dtype1)
print(arr)

print(np.sort(arr,order="name"))
print(np.sort(arr,order="gpa"))
print(np.sort(arr,order=["year","gpa"]))

[(b'Popo', 2007, 8.6) (b'Dodo', 2009, 6.7) (b'Lolo', 2004, 9.2)]
[(b'Dodo', 2009, 6.7) (b'Lolo', 2004, 9.2) (b'Popo', 2007, 8.6)]
[(b'Dodo', 2009, 6.7) (b'Popo', 2007, 8.6) (b'Lolo', 2004, 9.2)]
[(b'Lolo', 2004, 9.2) (b'Popo', 2007, 8.6) (b'Dodo', 2009, 6.7)]


In [21]:
trig = np.array([0, np.pi/2, np.pi, 1])
print(np.sin(trig))
print(np.cos(trig))
print(np.tan(trig))

[0.00000000e+00 1.00000000e+00 1.22464680e-16 8.41470985e-01]
[ 1.00000000e+00  6.12323400e-17 -1.00000000e+00  5.40302306e-01]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  1.55740772e+00]


In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [18]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])
print(arr2[2:7])
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3[0:2,1:3])

[3 4 5 6 7]
[[2 3]
 [5 6]]


In [17]:
print(arr1)
print(type(arr1))
print(arr2)
print(zero)
print(ones)

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]
 [9 7 5 3]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
arr1= np.array([1,2,3,4])
arr2= np.array([[1,2,3,4],[5,6,7,8],[9,7,5,3]])
zero= np.zeros((4,3))
ones = np.ones((3,4))

In [14]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 14.9 MB/s eta 0:00:01
   ---------- ----------------------------- 3.4/12.4 MB 12.2 MB/s eta 0:00:01
   --------------------- ------------------ 6.6/12.4 MB 12.9 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.4 MB 13.7 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 13.1 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 12.7 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
import numpy as np